### ISSUE TITLE
Async decorator typing regression in 2.4.0 with mypy disallow_any_decorated

### ISSUE THREAD

**Issue by MeisQuietude** [python-backoff/backoff#200]
## Summary

After migrating from `backoff==2.2.1` to `python-backoff==2.4.0`, applying `@backoff.on_exception` to an annotated async function fails with mypy when `disallow_any_decorated = true`.

Runtime behavior is unaffected. This is a static typing regression introduced by the decorator annotation changes in #182.

## Reproduction

`example.py`:

```python
import backoff


@backoff.on_exception(backoff.expo, ValueError)
async def fetch() -> str:
    return "ok"
```

`pyproject.toml`:

```toml
[tool.mypy]
strict = true
disallow_any_decorated = true
```

Run:

```console
mypy example.py
```

Result with `python-backoff==2.4.0` and mypy 2.3.0:

```text
example.py:5: error: Type of decorated function contains type "Any"
("Callable[[], Coroutine[Any, Any, str]]")  [misc]
```

The same example passes with `backoff==2.2.1`.

## Cause

Version 2.2.1 typed the decorator as an identity transformation over the complete callable type:

```python
_CallableT = TypeVar("_CallableT", bound=Callable[..., Any])

def on_exception(...) -> Callable[[_CallableT], _CallableT]:
    ...
```

Version 2.4.0 reconstructs the callable using `ParamSpec` and a return `TypeVar`:

```python
def on_exception(
    ...
) -> Callable[[Callable[P, T]], Callable[P, T]]:
    ...
```

Mypy represents an async function as `Callable[P, Coroutine[Any, Any, T]]`. After the new decorator transformation, `disallow_any_decorated` reports the two `Any` parameters of `Coroutine`.

This behavior is related to python/mypy#17171. However, the change in #182 makes `python-backoff` trigger the diagnostic where 2.2.1 did not.

There is also a separate problem in the internal async annotations. Both `_async.retry_exception` and `_async.retry_predicate` accept:

```python
target: Callable[P, T]
```

but then await the result:

```python
ret = await target(*args, **kwargs)
```

An arbitrary `T` is not awaitable. The returned async wrapper is also annotated as `Callable[P, T]`, although an `async def retry(...) -> T` returns a coroutine. These mismatches are currently hidden with `type: ignore`.

## Expected behavior

Decorating an annotated async function should:

- pass mypy with `disallow_any_decorated = true`;
- preserve its parameter and awaited result types;
- remain usable with APIs expecting a coroutine, such as `asyncio.create_task`;
- require no adapter or `type: ignore` in consumer code.

## Proposed approach

Keep the `ParamSpec`-based typing introduced in #182 inside the sync and async implementations, but expose the public decorator as an identity transformation over the complete callable type:

```python
_CallableT = TypeVar("_CallableT", bound=Callable[..., Any])


def on_exception(...) -> Callable[[_CallableT], _CallableT]:
    ...
```

The decorator preserves the callable's public contract, so retaining the complete callable type avoids reconstructing an async function as `Callable[P, Coroutine[Any, Any, T]]`.

This identity form is the exact public typing contract of 2.2.1, so consumer code that type-checked against 2.2.1 — including strict configurations with `disallow_any_decorated` — type-checks unchanged. It also gives up nothing that #182 delivered to consumers: an identity transformation preserves the complete callable type, so parameter and return checking at call sites stays at least as precise as with the reconstructed `Callable[P, T]` form, while the `ParamSpec` typing keeps doing its checking work inside the implementations. #182 states no rationale for reconstructing the public type, so no known requirement depends on that form.

Fixing this in the library also does not need to wait for python/mypy#17171: the identity annotation is accurate regardless of how mypy represents async callables, and consumers should not have to disable a strict flag that worked with 2.2.1.

An overloaded public protocol is not suitable here. Its async overload overlaps with the generic sync overload when a function has an unknown or unannotated return type. Pyrefly may therefore classify an unannotated sync function as async.

The internal implementations should retain `ParamSpec` and use separate sync and async contracts. The async implementation should accept a callable returning an awaitable or coroutine and declare that its wrapper returns a coroutine. The sync implementation should continue to use `Callable[P, T]`.

The same separation should be applied to `on_predicate`, `_async.retry_predicate`, and their sync counterparts.

Regression tests should type-check consumer code against the built package and cover:

- an annotated async function with mypy and `disallow_any_decorated = true`;
- preservation of the async function's parameter and result types;
- passing the decorated async call to `asyncio.create_task`;
- an unannotated sync function with pyrefly, ensuring it remains classified as sync.

## Environment

- Python 3.14
- mypy 2.3.0
- python-backoff 2.4.0

**Comment by edgarrmondragon** [comment]
Thanks for reporting @MeisQuietude !
